# -*- coding: utf-8 -*-
"""scibert_eda_cleaning_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GG3iv8eVU5nwEcvybikjKwsSp17D9pXY

# Análisis, Limpieza, Balanceo y Fine-tuning de SciBERT
## Clasificación de Función de Cita Científica

Proceso:

1. **Análisis exploratorio de datos (EDA)**: distribución de clases, longitud
   de textos, duplicados, valores nulos.
2. **Limpieza de datos**: normalización de texto, eliminación de duplicados.
3. **Balanceo de categorías**: diagnóstico del desbalance y estrategia de
   corrección.
4. **Fine-tuning de SciBERT** (`allenai/scibert_scivocab_uncased`) sobre las
   9 categorías de función de cita.
5. **Evaluación**: reporte de clasificación, matriz de confusión, guardado
   del modelo final.

---

**Versión con registro en MLflow.** Respecto del script original no se cambió
nada de la lógica ni de la estructura: mismas secciones, mismo orden, mismos
hiperparámetros. Lo único añadido es el registro en el servidor MLflow del
equipo, en el experimento `scibert_finetuning`:

- Parámetros (sección 12, al iniciar la corrida): `EPOCHS`, `BATCH_SIZE`,
  `LEARNING_RATE`, `model_base`, `balance_strategy`, `max_length`,
  `train_size`, `val_size`, `test_size`, `num_labels`.
- Métricas (sección 13, tras evaluar el test): `accuracy`, `f1_macro`,
  `precision_macro`, `recall_macro`, `f1_weighted`, `precision_weighted`,
  `recall_weighted`.

`TrainingArguments` conserva `report_to="none"` a propósito: con `"mlflow"` el
Trainer activaría el registro automático y llenaría la corrida de parámetros y
métricas por paso que aquí no se pidieron.

## 1. Importar librerías
"""

# !python --version

# from google.colab import drive
# drive.mount('/content/drive')

# !pip install mlflow transformers datasets torch scikit-learn pandas matplotlib seaborn accelerate mlflow --break-system-packages --quiet

import re
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix,
)
from sklearn.utils.class_weight import compute_class_weight

import mlflow

import torch
import torch.nn as nn
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    set_seed,
)

sns.set_theme(style="whitegrid")
pd.set_option("display.max_colwidth", 120)

"""## 2. Configuración"""

BASE_NAME = "final_labelled_citing_sentences_all"
INPUT_CSV = Path(f"/content/drive/MyDrive/Colab Notebooks/microproyecto/data/{BASE_NAME}.csv")
#INPUT_CSV = Path(f"/content/{BASE_NAME}.csv")

TEXT_COL = "citing-sentence"
LABEL_COL = "label"

MODEL_NAME = "allenai/scibert_scivocab_uncased"
OUTPUT_DIR = Path("/content/drive/MyDrive/Colab Notebooks/microproyecto/data/scibert-citation-function")

# Umbrales de limpieza por longitud del texto (en caracteres)
MIN_TEXT_LENGTH = 15
MAX_TEXT_LENGTH = 2000

RANDOM_SEED = 42
set_seed(RANDOM_SEED)

# --- Registro de experimentos en MLflow ---
# Servidor del equipo (instancia EC2). Responde en HTTP plano: `mlflow server
# --host 0.0.0.0 --port 8050` no habilita TLS por sí solo, así que https://
# fallaría. Para lanzar esto desde Colab, el puerto 8050 debe estar abierto en
# el security group para la IP saliente de Colab.
MLFLOW_TRACKING_URI = "http://44.211.66.20:8050"
MLFLOW_EXPERIMENT_NAME = "scibert_finetuning"

mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
experiment = mlflow.set_experiment(MLFLOW_EXPERIMENT_NAME)
print(f"MLflow: {MLFLOW_TRACKING_URI} | experimento "
      f"'{MLFLOW_EXPERIMENT_NAME}' (id={experiment.experiment_id})")

"""## 3. Carga del dataset"""

if not INPUT_CSV.exists():
    raise FileNotFoundError(
        f"No se encontró el archivo '{INPUT_CSV}'."
    )

df_raw = pd.read_csv(INPUT_CSV, dtype={"paper-id": str, "line-number": str})

print(f"Filas cargadas: {len(df_raw)}")
print(f"Columnas: {list(df_raw.columns)}")
df_raw.head(5)

"""## 4. Análisis exploratorio (EDA)

### 4.1 Nulos, duplicados, tipos de dato
"""

print("Info general del DataFrame:")
df_raw.info()

print("\nValores nulos por columna:")
print(df_raw.isnull().sum())

print(f"\nFilas totalmente duplicadas: {df_raw.duplicated().sum()}")
print(f"Duplicados exactos en '{TEXT_COL}': {df_raw[TEXT_COL].duplicated().sum()}")

"""### 4.2 Distribución de clases (label)"""

label_counts = df_raw[LABEL_COL].value_counts()
print(label_counts)

plt.figure(figsize=(9, 5))
sns.barplot(x=label_counts.values, y=label_counts.index, palette="viridis")
plt.title("Distribución de categorías de función de cita (antes de limpiar)")
plt.xlabel("Registros")
plt.ylabel("Categoría")
plt.tight_layout()
plt.show()

print(f"\nRatio desbalance (clase mayoritaria / clase minoritaria): "
      f"{label_counts.max() / label_counts.min():.2f}x")

"""### 4.3 Distribución de longitud del texto"""

df_raw["text_length"] = df_raw[TEXT_COL].astype(str).apply(len)
df_raw["word_count"] = df_raw[TEXT_COL].astype(str).apply(lambda t: len(t.split()))

print("Estadísticas de longitud de texto (caracteres):")
print(df_raw["text_length"].describe())

fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))

sns.histplot(df_raw["text_length"], bins=50, ax=axes[0], color="steelblue")
axes[0].axvline(MIN_TEXT_LENGTH, color="red", linestyle="--", label=f"min={MIN_TEXT_LENGTH}")
axes[0].axvline(MAX_TEXT_LENGTH, color="red", linestyle="--", label=f"max={MAX_TEXT_LENGTH}")
axes[0].set_title("Distribución de longitud (caracteres)")
axes[0].legend()

sns.boxplot(x=LABEL_COL, y="text_length", data=df_raw, ax=axes[1])
axes[1].set_title("Longitud de texto por categoría")
axes[1].tick_params(axis="x", rotation=75)

plt.tight_layout()
plt.show()

print(f"\nRegistros con longitud < {MIN_TEXT_LENGTH}: "
      f"{(df_raw['text_length'] < MIN_TEXT_LENGTH).sum()}")
print(f"Registros con longitud > {MAX_TEXT_LENGTH}: "
      f"{(df_raw['text_length'] > MAX_TEXT_LENGTH).sum()}")

"""## 5. Limpieza de datos

Pasos aplicados:
1. Eliminar filas con texto o etiqueta nula/vacía.
2. Normalizar espacios en blanco (colapsar espacios múltiples, quitar saltos de línea sobrantes).
3. Eliminar duplicados exactos en `citing-sentence` (mismo texto + misma etiqueta).
4. Filtrar textos demasiado cortos (probable ruido/truncamiento) o demasiado largos (probable error de parseo).
5. Verificar que las etiquetas correspondan exactamente a las 9 categorías esperadas.
"""

EXPECTED_LABELS = {
    "Background",
    "Further Reading",
    "Evidence",
    "Basis",
    "Application",
    "Improvement / Modification",
    "Identification of the Originator",
    "Gap",
    "Comparison",
}

def normalize_whitespace(text: str) -> str:
    text = str(text)
    text = text.replace("\n", " ").replace("\r", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


df = df_raw.copy()
n_inicial = len(df)

# 1. Nulos / vacíos
df = df.dropna(subset=[TEXT_COL, LABEL_COL])
df = df[df[TEXT_COL].astype(str).str.strip() != ""]
n_tras_nulos = len(df)

# 2. Normalizar texto
df[TEXT_COL] = df[TEXT_COL].apply(normalize_whitespace)
df[LABEL_COL] = df[LABEL_COL].astype(str).str.strip()

# 3. Duplicados exactos (texto + etiqueta)
df = df.drop_duplicates(subset=[TEXT_COL, LABEL_COL])
n_tras_duplicados = len(df)

# 4. Filtrar por longitud
df["text_length"] = df[TEXT_COL].apply(len)
df = df[(df["text_length"] >= MIN_TEXT_LENGTH) & (df["text_length"] <= MAX_TEXT_LENGTH)]
n_tras_longitud = len(df)

# 5. Verificar etiquetas válidas
etiquetas_invalidas = set(df[LABEL_COL].unique()) - EXPECTED_LABELS
if etiquetas_invalidas:
    print(f"ADVERTENCIA: etiquetas inesperadas encontradas: {etiquetas_invalidas}")
    df = df[df[LABEL_COL].isin(EXPECTED_LABELS)]
n_final = len(df)

print("Resumen:")
print(f"  Filas iniciales:                    {n_inicial}")
print(f"  Tras eliminar nulos/vacíos:         {n_tras_nulos}  (-{n_inicial - n_tras_nulos})")
print(f"  Tras eliminar duplicados:           {n_tras_duplicados}  (-{n_tras_nulos - n_tras_duplicados})")
print(f"  Tras filtrar por longitud:          {n_tras_longitud}  (-{n_tras_duplicados - n_tras_longitud})")
print(f"  Tras validar etiquetas:             {n_final}  (-{n_tras_longitud - n_final})")
print(f"\n  Total descartado: {n_inicial - n_final} filas ({(n_inicial - n_final) / n_inicial * 100:.1f}%)")

df = df.reset_index(drop=True)
df[[TEXT_COL, LABEL_COL]].head(10)

"""### 5.1 Distribución de clases después de la limpieza"""

label_counts_clean = df[LABEL_COL].value_counts()
print(label_counts_clean)

plt.figure(figsize=(9, 5))
sns.barplot(x=label_counts_clean.values, y=label_counts_clean.index, palette="mako")
plt.title("Distribución de categorías después de la limpieza")
plt.xlabel("Registros")
plt.ylabel("Categoría")
plt.tight_layout()
plt.show()

"""## 6. Balanceo de categorías

El desbalance de clases es muy notorio, pero debido a la complejidad del texto aplicaremos la estratégia de balanceo **`class_weights`** donde penalizamos más el error en clases minoritarias durante el entrenamiento, ajustando la función de pérdida. Lo que nos permite evitar le riesgo de overfitting por duplicación de información.
"""

# Estrategia de balanceo.
BALANCE_STRATEGY = "class_weights"

class_weights_tensor = None

df_balanced = df.copy()

"""## 7. Mapeo de etiquetas a IDs numéricos"""

labels_sorted = sorted(df_balanced[LABEL_COL].unique().tolist())
label2id = {label: idx for idx, label in enumerate(labels_sorted)}
id2label = {idx: label for label, idx in label2id.items()}
num_labels = len(labels_sorted)

print(f"Esquema de etiquetas ({num_labels} clases):")
for label, idx in label2id.items():
    print(f"  {idx}: {label}")

df_balanced["label_id"] = df_balanced[LABEL_COL].map(label2id)

"""## 8. División train / validation / test (estratificada)"""

TEST_SIZE = 0.15
EVAL_SIZE = 0.15

train_df, temp_df = train_test_split(
    df_balanced,
    test_size=(TEST_SIZE + EVAL_SIZE),
    stratify=df_balanced["label_id"],
    random_state=RANDOM_SEED,
)

relative_test_size = TEST_SIZE / (TEST_SIZE + EVAL_SIZE)
val_df, test_df = train_test_split(
    temp_df,
    test_size=relative_test_size,
    stratify=temp_df["label_id"],
    random_state=RANDOM_SEED,
)

print(f"Train:      {len(train_df)} ejemplos")
print(f"Validation: {len(val_df)} ejemplos")
print(f"Test:       {len(test_df)} ejemplos")

"""## 9. Cálculo de pesos por clase

Los pesos se calculan **solo sobre el set de entrenamiento**, para no filtrar
información del set de validación/test hacia el proceso de entrenamiento.
"""

weights_array = compute_class_weight(
    class_weight="balanced",
    classes=np.arange(num_labels),
    y=train_df["label_id"].values,
)
class_weights_tensor = torch.tensor(weights_array, dtype=torch.float)

print("Pesos calculados por clase (mayor peso = clase más rara):")
for idx, w in enumerate(weights_array):
    print(f"  {id2label[idx]:40s} -> peso: {w:.3f}")

"""## 9.1 Diagnóstico: longitud en tokens

Analizamos la cantidad de tokens necesaria para SciBERT tokenizando una muestra real del dataset para conocer la distribución exacta
en tokens.
"""

from transformers import AutoTokenizer

_diag_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Muestra para medir longitud real
sample_size = min(20000, len(df_balanced))
sample_texts = df_balanced[TEXT_COL].sample(sample_size, random_state=RANDOM_SEED).tolist()

token_lengths = [
    len(_diag_tokenizer.encode(t, add_special_tokens=True)) for t in sample_texts
]
token_lengths = np.array(token_lengths)

percentiles = [50, 75, 90, 95, 99, 100]
print(f"Longitud en TOKENS (muestra de {sample_size} ejemplos):")
for p in percentiles:
    print(f"  Percentil {p:>3}: {np.percentile(token_lengths, p):.1f} tokens")

print(f"\n  Media:  {token_lengths.mean():.1f} tokens")
print(f"  Máximo: {token_lengths.max()} tokens")

plt.figure(figsize=(9, 4.5))
sns.histplot(token_lengths, bins=50, color="darkorange")
for candidate in [64, 128, 192, 256]:
    pct_covered = (token_lengths <= candidate).mean() * 100
    plt.axvline(candidate, linestyle="--", alpha=0.6,
                label=f"MAX_LENGTH={candidate} (cubre {pct_covered:.1f}%)")
plt.title("Distribución de longitud tokenizada (SciBERT)")
plt.xlabel("Cantidad de tokens")
plt.legend()
plt.tight_layout()
plt.show()

"""## 10. Tokenización con SciBERT

Seleccionamos 128 porque cubre la mayoría de los casos según el análisis anterior y tiene un menor costo computacional que 256.
"""

MAX_LENGTH = 128

print(f"Cargando tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)


def to_hf_dataset(pdf: pd.DataFrame) -> Dataset:
    return Dataset.from_pandas(
        pdf[[TEXT_COL, "label_id"]].rename(columns={TEXT_COL: "text", "label_id": "labels"})
    )


train_ds = to_hf_dataset(train_df)
val_ds = to_hf_dataset(val_df)
test_ds = to_hf_dataset(test_df)


def tokenize_fn(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=MAX_LENGTH)


train_ds = train_ds.map(tokenize_fn, batched=True)
val_ds = val_ds.map(tokenize_fn, batched=True)
test_ds = test_ds.map(tokenize_fn, batched=True)

columns = ["input_ids", "attention_mask", "labels"]
train_ds.set_format(type="torch", columns=columns)
val_ds.set_format(type="torch", columns=columns)
test_ds.set_format(type="torch", columns=columns)

print("Tokenización completada.")

"""## 11. Modelo y Trainer

Se define la clase `WeightedTrainer` que sobreescribe el cálculo de la pérdida para
aplicar `class_weights`.
"""

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Dispositivo de entrenamiento: {device}")


class WeightedTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        if self.class_weights is not None:
            loss_fct = nn.CrossEntropyLoss(weight=self.class_weights.to(logits.device))
        else:
            loss_fct = nn.CrossEntropyLoss()

        loss = loss_fct(logits.view(-1, num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average="macro", zero_division=0
    )
    precision_w, recall_w, f1_w, _ = precision_recall_fscore_support(
        labels, preds, average="weighted", zero_division=0
    )
    return {
        "accuracy": acc,
        "f1_macro": f1_macro,
        "precision_macro": precision_macro,
        "recall_macro": recall_macro,
        "f1_weighted": f1_w,
        "precision_weighted": precision_w,
        "recall_weighted": recall_w,
    }

"""## 12. Configuración y ejecución del entrenamiento"""

EPOCHS = 1
BATCH_SIZE = 16
LEARNING_RATE = 2e-5

steps_per_epoch = max(1, len(train_ds) // BATCH_SIZE)
total_steps = steps_per_epoch * EPOCHS
warmup_steps = int(0.1 * total_steps)

SAVE_STEPS = max(200, steps_per_epoch // 10)

print(f"Pasos por época: {steps_per_epoch}")
print(f"Pasos totales:   {total_steps}")
print(f"Warmup steps (10%): {warmup_steps}")
print(f"Guardando checkpoint cada {SAVE_STEPS} pasos")

training_args = TrainingArguments(
    output_dir=str(OUTPUT_DIR),
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    warmup_steps=warmup_steps,
    eval_strategy="steps",
    eval_steps=SAVE_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    logging_strategy="steps",
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    save_total_limit=2,
    report_to="none",
    seed=RANDOM_SEED,
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics,
    class_weights=class_weights_tensor,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

import glob

# Detección automática de checkpoints previos (por si Colab se desconectó
# en una corrida anterior). Si existe al menos uno, se reanuda desde ahí
# en vez de empezar de cero.
existing_checkpoints = sorted(
    glob.glob(str(OUTPUT_DIR / "checkpoint-*")),
    key=lambda p: int(p.split("-")[-1]),
)

resume_from = existing_checkpoints[-1] if existing_checkpoints else None

if resume_from:
    print(f"Checkpoint previo encontrado, reanudando desde: {resume_from}")
else:
    print("No se encontraron checkpoints previos. Iniciando entrenamiento desde cero.")

# Se abre la corrida de MLflow justo antes de entrenar, que es cuando ya están
# definidos todos los parámetros que se quieren registrar. Se usa la forma
# imperativa (start_run / end_run) en vez de un `with`, para no tener que
# indentar el resto del script.
mlflow.start_run(
    experiment_id=experiment.experiment_id,
    run_name=f"scibert-e{EPOCHS}-b{BATCH_SIZE}-lr{LEARNING_RATE}",
)

mlflow.log_param("EPOCHS", EPOCHS)
mlflow.log_param("BATCH_SIZE", BATCH_SIZE)
mlflow.log_param("LEARNING_RATE", LEARNING_RATE)
mlflow.log_param("model_base", MODEL_NAME)
mlflow.log_param("balance_strategy", BALANCE_STRATEGY)
mlflow.log_param("max_length", MAX_LENGTH)
mlflow.log_param("train_size", len(train_df))
mlflow.log_param("val_size", len(val_df))
mlflow.log_param("test_size", len(test_df))
mlflow.log_param("num_labels", num_labels)

print("\nIniciando fine-tuning de SciBERT...\n")
train_result = trainer.train(resume_from_checkpoint=resume_from)

print("\nEntrenamiento finalizado.")
print(train_result.metrics)

"""## 13. Evaluación sobre el conjunto de test"""

test_predictions = trainer.predict(test_ds)
preds = np.argmax(test_predictions.predictions, axis=-1)
true_labels = test_predictions.label_ids

target_names = [id2label[i] for i in range(num_labels)]
report = classification_report(true_labels, preds, target_names=target_names, zero_division=0)

print("Reporte de clasificación (test):\n")
print(report)

# --- Registro de las métricas de test en MLflow ---
# `trainer.predict` aplica `compute_metrics` y devuelve las métricas con el
# prefijo "test_"; se registran con el nombre limpio.
METRICAS_MLFLOW = [
    "accuracy",
    "f1_macro",
    "precision_macro",
    "recall_macro",
    "f1_weighted",
    "precision_weighted",
    "recall_weighted",
]

test_metrics = test_predictions.metrics or {}

print("\nMétricas registradas en MLflow:")
for nombre in METRICAS_MLFLOW:
    valor = test_metrics.get(f"test_{nombre}", test_metrics.get(nombre))
    if valor is None:
        print(f"  {nombre}: no disponible en trainer.predict")
        continue
    mlflow.log_metric(nombre, float(valor))
    print(f"  {nombre}: {valor:.4f}")

"""### 13.1 Matriz de confusión"""

cm = confusion_matrix(true_labels, preds)
cm_df = pd.DataFrame(cm, index=target_names, columns=target_names)

plt.figure(figsize=(10, 8))
sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de confusión — Test set")
plt.ylabel("Etiqueta real")
plt.xlabel("Etiqueta predicha")
plt.xticks(rotation=75)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""## 14. Guardar modelo, tokenizer y metadatos"""

final_dir = OUTPUT_DIR / "model_scibert_citing_sentences"
final_dir.mkdir(parents=True, exist_ok=True)

trainer.save_model(str(final_dir))
tokenizer.save_pretrained(str(final_dir))

with open(final_dir / "label_mapping.json", "w", encoding="utf-8") as f:
    json.dump({"label2id": label2id, "id2label": id2label}, f, ensure_ascii=False, indent=2)

with open(final_dir / "test_classification_report.txt", "w", encoding="utf-8") as f:
    f.write(report)

metadata = {
    "model_base": MODEL_NAME,
    "balance_strategy": BALANCE_STRATEGY,
    "max_length": MAX_LENGTH,
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "learning_rate": LEARNING_RATE,
    "train_size": len(train_df),
    "val_size": len(val_df),
    "test_size": len(test_df),
    "num_labels": num_labels,
}
with open(final_dir / "training_metadata.json", "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

print(f"Modelo, tokenizer, mapeo de etiquetas y metadatos guardados en: {final_dir.resolve()}")

"""## 15. Cierre de la corrida en MLflow"""

mlflow.end_run(status="FINISHED")

run_id = mlflow.last_active_run().info.run_id
print(f"Corrida registrada en MLflow: {MLFLOW_TRACKING_URI}"
      f"/#/experiments/{experiment.experiment_id}/runs/{run_id}")